FIGO-783 rename teknisk-dokumentasjon til kom i gang. Sett inn sekven…
Skatteetaten/beta-apier pull request #57
Opened 2024-09-23 12:34 UTC by jakobskatt

…sdiagrammer og legg til funksjonell beskrivelse.

2024-09-24 07:52 UTC, GodagerSindre requested changes
Flott å få inn figurer og ekstra informasjon for de som er nysgjerrige på det. Blitt enda mer tydelig dokumentert nå 👍

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/beskrivelse-av-tjenester.md
> +### Sekvensdiagram
Link til denne burde kanskje være i innholdsfortegnelse mtp at alle andre underoverskifter er der og i menyen som havner til høyre i skjermbildet. Gjelder alle de andre stedene det også er sekvensdiagram

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/beskrivelse-av-tjenester.md
> +### Sekvensdiagram
Synes figurer som dette burde komme etter teksten som forklarer de samme tingene, slik at man har kontekst for figuren først, og så får en fullstendig visuell oversikt til slutt som tilskudd til forklaringene. Tenker derfor dette diagrammet og de to andre diagrammene i fila kan plasseres til slutt under hovedoverskriften de tilhører

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/funksjonell-beskrivelse.md
> +| Oppdragsgivers kravidentifikator      | ja           | Dette er en unik id til pengekravet hos oppdragsgiver. Oppdragsgivers kravidentifikator brukes i avstemming av overførte krav fra oppdragsgive
Denne er ikke påkrevd i API-et vårt så bør vel stå nei her.

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/funksjonell-beskrivelse.md
> +| Oppdragsgivers referanse              | ja           | Dette er oppdragsgivers referanse til saken hvor pengekravet er fastsatt, eksempelvis et saksnummer. Denne referansen kan brukes når det skal
*hvilke**n** sak

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/funksjonell-beskrivelse.md
> +| Fastsettelsesdato                     | ja           | Med fastsettelsesdato menes dato da pengekravet oppsto/ble fastsatt av oppdragsgiver, eksempelvis dato da vedtaket for kravet ble fattet (vedt
vet*

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/funksjonell-beskrivelse.md
> +| Skyldner                              | ja           | Den som er pliktig til å betale kravet, det kan enten være en virksomhet eller privatperson og da oppgis organisasjonsnummeret til virksomhete
Litt tung setning, så hva med å dele den opp slik: 

Privatpersonen eller virksomheten som er pliktig til å betale kravet. For privatpersoner oppgis fødsels- og personnummeret eller d-nummer, og for virksomheter oppgis organisasjonsnummer.

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/funksjonell-beskrivelse.md
> +| Kravtype                              | ja           | Samlebetegnelse på kravene som skal kreves inn, eksempelvis tvangsmulkt eller overtredelsesgebyr.
Noen grunn til at det er krav i flertall her?

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/funksjonell-beskrivelse.md
> +| Foreldelsesfristens utgangspunkt      | nei          | Datoen når foreldelsesfristen på kravet starter å løpe. I mange tilfeller er denne datoen det samme datoen som fastsettelsesdatoen. Foreldelse
den samme*

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/kom-i-gang.md
> +# Kom i gang
Mer fornuftig overskrift dette 👍

2024-09-24 07:52 UTC, GodagerSindre commented on docs/innkrevingsoppdrag/kom-i-gang.md
> +![](../../static/download/innkrevingsoppdrag/tjenester_oppdragsinnkreving.png)
Nice å få med denne 👍

2024-09-24 13:47 UTC, jakobskatt commented on docs/innkrevingsoppdrag/funksjonell-beskrivelse.md
> +| Oppdragsgivers kravidentifikator      | ja           | Dette er en unik id til pengekravet hos oppdragsgiver. Oppdragsgivers kravidentifikator brukes i avstemming av overførte krav fra oppdragsgive
Godt sett!

2024-09-25 14:26 UTC, GodagerSindre approved these changes

2024-09-25 14:26 UTC, merged